name: Mark stale issues and pull requests

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: self-hosted

    steps:
      - uses: actions/stale@v3.0.18
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-label: 'stale'
